import type { Metadata } from "next";
import { Inter } from "next/font/google";

import DiscordSessionProvider from "@/components/util/DiscordSessionProvider";
import Topbar from "@/components/compound/Topbar";
import { ThemeProvider } from "@/components/util/ThemeProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <DiscordSessionProvider>
            <Topbar />
            {children}
          </DiscordSessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
