import type { Metadata } from "next";
import { Inter } from "next/font/google";
import DiscordSessionProvider from "@/components/compound/DiscordSessionProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DiscordSessionProvider>{children}</DiscordSessionProvider>
      </body>
    </html>
  );
}
