name: Deploy to Vercel & Neon

on:
  push:
    branches:
      - main
      - prev
  pull_request:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions: write-all
    environment: default

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7

      - name: Install the Neon CLI
        run: npm install -g neonctl

      - name: Create a Neon branch if not exists
        id: create-branch
        uses: neondatabase/create-branch-action@v4
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch_name: ${{ steps.branch-name.outputs.current_branch }}
          api_key: ${{ secrets.NEON_API_KEY }}
          username: ${{ secrets.PGUSER }}
          database: ${{ secrets.PGDATABASE }}
          prisma: true

      - name: Write Database URLs to .env
        run: |
          touch .env

          echo 'DATABASE_URL=${{ steps.create-branch.outputs.db_url_with_pooler }}' >> .env

          echo 'DIRECT_DATABASE_URL=${{ steps.create-branch.outputs.db_url }}' >> .env

      - name: Check If Prisma Schema is Modified
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            prisma:
              - 'prisma/**'

      - name: Install Prisma
        if: steps.changes.outputs.prisma == 'true'
        run: npm install

      - name: Run Prisma Migrate
        if: steps.changes.outputs.prisma == 'true'
        run: |
          npm run gen
          npm run migrate:prod

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy Project to Vercel (Preview)
        id: deploy-prev
        if: steps.branch-name.outputs.current_branch != 'main'
        run: echo preview_url=$(vercel deploy --yes --token=${{ secrets.VERCEL_TOKEN }}) >> $GITHUB_OUTPUT

      - name: Deploy Project to Vercel (Production)
        if: steps.branch-name.outputs.current_branch == 'main'
        run: vercel deploy --yes --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Comment on pull request
        if: steps.branch-name.outputs.current_branch != 'main' && github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            * Vercel Preview URL: ${{ steps.deploy-prev.outputs.preview_url }}
              - add it to the allowed redirect URIs on https://discord.com/developers/applications/
            * Neon branch '${{ steps.branch-name.outputs.current_branch }}' is successfully created
