name: Deploy to Vercel & Neon

on:
  push:
    branches:
      - main
      - prev
  pull_request:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions: write-all
    environment: default

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7

      - name: Install the Neon CLI
        run: npm install -g neonctl

      - name: Create a Neon branch if not exists
        id: create-branch
        uses: neondatabase/create-branch-action@v4
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch_name: ${{ steps.branch-name.outputs.current_branch }}
          api_key: ${{ secrets.NEON_API_KEY }}
          username: ${{ secrets.PGUSER }}
          database: ${{ secrets.PGDATABASE }}
          prisma: true

      - name: Run Prisma Migrate
        run: |
          touch .env

          echo 'DATABASE_URL=${{ steps.create-branch.outputs.db_url_with_pooler }}' >> .env

          echo 'DIRECT_DATABASE_URL=${{ steps.create-branch.outputs.db_url }}' >> .env

          npx prisma generate
          npx prisma migrate deploy

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information (Preview)
        if: steps.branch-name.outputs.current_branch != 'main'
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull Vercel Environment Information (Production)
        if: steps.branch-name.outputs.current_branch == 'main'
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts (Preview)
        if: steps.branch-name.outputs.current_branch != 'main'
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts (Production)
        if: steps.branch-name.outputs.current_branch == 'main'
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel (Preview)
        id: deploy-prev
        if: steps.branch-name.outputs.current_branch != 'main'
        run: echo preview_url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}) >> $GITHUB_OUTPUT

      - name: Deploy Project Artifacts to Vercel (Production)
        if: steps.branch-name.outputs.current_branch == 'main'
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Comment on pull request
        if: steps.branch-name.outputs.current_branch != 'main' && github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Vercel Preview URL :rocket: : ${{ steps.deploy-prev.outputs.preview_url }}
            Neon branch :elephant: : https://console.neon.tech/app/projects/${{ secrets.NEON_PROJECT_ID }}/branches/${{ steps.branch-name.outputs.current_branch }}
